name: Regular Visual Testing
on:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight UTC
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run visual testing
        run: npm run cy:percy
        env: PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}
      - name: Run Component visual Testing
        run: npm run percy
